# Generated by Django 4.2.29 on 2026-03-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('water_body', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SensorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('safe_min', models.FloatField()),
                ('safe_max', models.FloatField()),
                ('is_real', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('nitrates', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('risk', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='RegionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('prediction_text', models.TextField()),
                ('next_risk', models.CharField(choices=[('rising', 'Rising'), ('falling', 'Falling'), ('stable', 'Stable')], max_length=10)),
                ('contamination_probability', models.IntegerField()),
                ('top_concern', models.CharField(max_length=100)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_days', to='api.regionprediction')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=10, unique=True)),
                ('time_label', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('risk', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
