# Generated by Django 6.0.5 on 2026-05-16 22:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('shapefile', 'Shapefile'), ('epanet', 'EPANET .inp')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('complete_warnings', 'Complete with Warnings'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='WaterNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_crs', models.CharField(blank=True, max_length=50)),
                ('bbox', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('total_length_km', models.FloatField(blank=True, null=True)),
                ('total_pipes', models.IntegerField(default=0)),
                ('total_nodes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='core.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('upload', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.networkupload')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('pump', 'Pump'), ('valve', 'Valve'), ('meter', 'Flow Meter'), ('treatment_plant', 'Treatment Plant'), ('borehole', 'Borehole'), ('intake', 'Water Intake'), ('storage_tank', 'Storage Tank')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(default='active', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='networks.waternetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('population_estimate', models.IntegerField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='networks.waternetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('node_type', models.CharField(choices=[('junction', 'Junction'), ('reservoir', 'Reservoir'), ('tank', 'Tank'), ('meter', 'Meter')], default='junction', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('demand_lps', models.FloatField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='networks.waternetwork')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='networks.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('material', models.CharField(choices=[('PVC', 'PVC'), ('GI', 'Galvanized Iron'), ('HDPE', 'HDPE'), ('Steel', 'Steel'), ('PPR', 'PPR'), ('CI', 'Cast Iron'), ('AC', 'Asbestos Cement'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('diameter_mm', models.FloatField(blank=True, null=True)),
                ('roughness', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('out_of_service', 'Out of Service'), ('pending', 'Pending')], default='open', max_length=20)),
                ('installation_year', models.IntegerField(blank=True, null=True)),
                ('network_type', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipes', to='networks.waternetwork')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipes', to='networks.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['network', 'zone', 'status', 'material'], name='networks_pi_network_e25af6_idx')],
            },
        ),
    ]
