# Generated by Django 6.0.5 on 2026-05-16 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0001_initial'),
        ('networks', '0001_initial'),
        ('sensors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_models', to='networks.waternetwork'),
        ),
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_models', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='affected_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='networks.zone'),
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_events', to='networks.waternetwork'),
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_events', to='sensors.sensor'),
        ),
        migrations.AddField(
            model_name='leakriskscore',
            name='pipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leak_risk', to='networks.pipe'),
        ),
    ]
