# Generated by Django 6.0.5 on 2026-05-16 22:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTBroker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('topic_prefix', models.CharField(default='aquawise', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_brokers', to='core.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(choices=[('pressure', 'Pressure'), ('flow', 'Flow Rate'), ('turbidity', 'Turbidity'), ('ph', 'pH'), ('chlorine', 'Chlorine'), ('tds', 'Total Dissolved Solids'), ('temperature', 'Temperature')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('unit', models.CharField(default='bar', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('associated_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='networks.node')),
                ('associated_pipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='networks.pipe')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='networks.waternetwork')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='core.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('quality_flag', models.CharField(choices=[('good', 'Good'), ('suspect', 'Suspect'), ('bad', 'Bad')], default='good', max_length=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', 'timestamp'], name='sensors_sen_sensor__6ce6a7_idx')],
            },
        ),
    ]
