# Generated by Django 6.0.5 on 2026-05-16 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('networks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('inp_file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('wntr_version', models.CharField(blank=True, max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='networks.waternetwork')),
            ],
        ),
        migrations.CreateModel(
            name='HydraulicScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('modifications', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='networks.waternetwork')),
                ('base_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_scenarios', to='hydraulics.simulationrun')),
            ],
        ),
        migrations.CreateModel(
            name='PressureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_external_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pressure_m', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_results', to='hydraulics.simulationrun')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['run', 'node_external_id', 'timestamp'], name='hydraulics__run_id_efc86e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipe_external_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('flow_lps', models.FloatField()),
                ('velocity_mps', models.FloatField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_results', to='hydraulics.simulationrun')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['run', 'pipe_external_id', 'timestamp'], name='hydraulics__run_id_330542_idx')],
            },
        ),
    ]
