# Generated by Django 6.0.5 on 2026-05-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkupload',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='networks.waternetwork'),
        ),
        migrations.AlterField(
            model_name='networkupload',
            name='file_type',
            field=models.CharField(choices=[('shapefile', 'Shapefile'), ('epanet', 'EPANET .inp'), ('epanet_inp', 'EPANET .inp'), ('epanet_net', 'EPANET .net')], max_length=20),
        ),
    ]
