# Generated by Django 6.0.5 on 2026-05-16 22:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(default='IsolationForest', max_length=50)),
                ('model_path', models.CharField(max_length=500)),
                ('training_start', models.DateTimeField()),
                ('training_end', models.DateTimeField()),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('contamination_rate', models.FloatField(default=0.05)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('pressure_drop', 'Pressure Drop'), ('pressure_spike', 'Pressure Spike'), ('flow_imbalance', 'Flow Imbalance'), ('quality_deviation', 'Quality Deviation'), ('sensor_fault', 'Sensor Fault')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('confidence', models.FloatField()),
                ('detected_at', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='LeakRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField()),
                ('risk_decile', models.IntegerField()),
                ('material_age_score', models.FloatField(blank=True, null=True)),
                ('pressure_variance_score', models.FloatField(blank=True, null=True)),
                ('historical_break_score', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
